### ISSUE TITLE
reference coefficients in Eq.4

### ISSUE THREAD

**Issue by Yzichen** [ChenhongyiYang/WidthFormer#2]
In Eq.4, ‘s’ denotes the coefficient for each reference point, but in Section 3.1, a number of ‘s’ appear, but they do not seem to represent reference coefficients and they seem to indicate the positional encoding.

So can you explain what the ‘s’ actually stands for?

**Comment by ChenhongyiYang** [comment]
Hi, I am sorry that the "s" is a typo. We have fixed it in the latest version of our paper.

**Comment by Yzichen** [comment]
In addition, I think there is an inconsistency between Equation 4 and Figure 2.  In Eq. 4, all encodings (d, sin, cos, z) for each reference point are weighted using reference coefficients. But in Figure 2, only the depth encoding (d) is weighted.

I don't know if I understand correctly, I hope this helps.

**Comment by WYL-Projects** [comment]
@Yzichen In reading the paper, I also found this problem.
![image](https://github.com/ChenhongyiYang/WidthFormer/assets/50573960/014fd95f-beba-4b70-a3ff-40cdcbb0fa45)
The yellow box seems to represent the distance PE, but I don't understand that after Fourier coding it becomes D×C dimensional, and I don't know why the reference coefficients (red box) are added to the distance PE, aren't the reference coefficients in the MLP?

**Comment by WYL-Projects** [comment]
@ChenhongyiYang Hi, where is the latest version of the paper?

**Comment by ChenhongyiYang** [comment]
Sorry for the incontinence. We largely rephrased the method section before we Arxiving the paper, so there were a lot of typos and inconsistencies between the figures and formulations. We are continuing to fix them and update the paper. 

@Yzichen  For your concerns, for Figure 2 (a), you are correct that the heights are also weighted here, and we will fix this later. For rotation PE, we do not need to explicitly weight it because all lifted 3D pixels from the same 2D pixels share the same rotation. For Figure 2 (b), we also do not need to compute the rotation PE for all lifted 3D pixels from an image column because they are all the same. 

@WYL-Projects For your concerns, in Figure 2 (a) we are actually showing how we compute the PE for a 2D image pixel (shown in the small red box). Therefore, given a pixel, after we lift it, we will get D 3D pixels. Then after the Fourier encoding, the shape of PE becomes D x C. Also, the MLP we showed here is used to fuse the PE for different parts (distance, rotation, height), and the reference coefficients are actually predicted by another conv layer (not explicitly shown here).

**Comment by WYL-Projects** [comment]
@ChenhongyiYang Okay, thanks for the reply. Since the rotational PE is not explicitly weighted, what PE does the green box represent and what PE does the yellow box represent?

**Comment by WYL-Projects** [comment]
@ChenhongyiYang Okay, thanks for the reply. Since the rotational PE is not explicitly weighted, what PE does the green box represent and what PE does the yellow box represent?
![image](https://github.com/ChenhongyiYang/WidthFormer/assets/50573960/c1f7ac0b-fe6e-413d-b298-3ca40196b552)

**Comment by WYL-Projects** [comment]
Sorry to bother you, I have another small question, I see that RefPE is converting multiple views to LIDAR coordinate system uniformly, why is it PE with the self vehicle as the origin again, this process is converting the point coordinates under LIDAR coordinate system to the self vehicle coordinate system centered on the rear axle of the vehicle again?
![image](https://github.com/ChenhongyiYang/WidthFormer/assets/50573960/6c6a5240-a646-4e7f-8e2f-a15107180d14)
